# .github/workflows/clang-tidy.yml
name: "clang-tidy CI"

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  tidy-check:
    runs-on: ubuntu-latest

    steps:
      # 1st Check the code
      - uses: actions/checkout@v3

      # 2nd install needed tool
      - name: Install LLVM/Clang
        run: |
          sudo apt update
          sudo apt install -y clang-tidy 

      - name: Compile Code
        working-directory: ${{ github.workspace }}
        run: |
          mkdir -p build
          cd build
          cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build Code
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake --build . -j4 

      # 5. Run clang-tidy via run-clang-tidy script
      - name: Run clang-tidy
        working-directory: ${{ github.workspace }}/build
        run: |
          # You can adjust -j <cores> or other flags as needed
          run-clang-tidy \
            -warnings-as-errors=* \
            -use-color \
            -p . \
            -j 4 \
            "sammine-lang/(src|include).*"
